### ISSUE TITLE
No default definition for handle_usb_setup()

### ISSUE THREAD

**Issue by elfmimi** [whitequark/libfx2#7]
I believe handle_usb_request() defined in [defusbsetup.c](https://github.com/whitequark/libfx2/blob/master/firmware/library/defusbsetup.c) is meant to be handle_usb_setup() instead.
```diff
- void handle_usb_request(__xdata struct usb_req_setup *request) {
+ void handle_usb_setup(__xdata struct usb_req_setup *request) {
```

**Comment by whitequark** [comment]
Thanks!
