### ISSUE TITLE
Example "boot-cypress" doesn't start after FW upload to FX2

### ISSUE THREAD

**Issue by Ho-Ro** [whitequark/libfx2#9]
The hex file is uploaded and the 8051 comes out of reset, but the FX2 doesn't re-enumerate.

Fix: change `usb_init(/*disconnect=*/false);` to `  usb_init(/*disconnect=*/true);` in this line:
https://github.com/whitequark/libfx2/blob/60fc41da3ded4aa66ab63312804fb68c3cc3014a/firmware/boot-cypress/main.c#L199

**Comment by whitequark** [comment]
That's actually not an example, it's a firmware that's used internally by `fx2tool`. With your fix, `fx2tool -B` will stop working.

**Comment by Ho-Ro** [comment]
Ok, understood - close.
A comment could be helpful - I started from [this point](https://libfx2.readthedocs.io/en/latest/getting_started.html#interacting-over-usb) without success while the other parts started up as (I) expected, e.g. boot-uf2:
https://github.com/whitequark/libfx2/blob/60fc41da3ded4aa66ab63312804fb68c3cc3014a/firmware/boot-uf2/main.c#L201-L202

**Comment by whitequark** [comment]
Clarified in https://github.com/whitequark/libfx2/commit/d98e54a823ee7841bff1c7b5a915c2e0b33342f6.
